# Consider the below code to answer further questions: 
      import numpy as np
      list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
      array_list = np.array(object = list_)

# Q1. 
**Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

## Difference Between List and Array in Python
## List
(1): Can consist of elements belonging to different data types

(2): No need to explicitly import a module for the declaration

(3): Cannot directly handle arithmetic operations

(4): Preferred for a shorter sequence of data items

(5): Consume larger memory for easy addition of elements

## Array

(1): Only consists of elements belonging to the same data type

(2): Need to explicitly import the array module for declaration

(3): Can directly handle arithmetic operations

(4): Preferred for a longer sequence of data items

(5): Comparatively more compact in memory size





In [1]:
# creating a list containing elements
# belonging to different data types
sample_list = [1, "Yash", ['a', 'e']]
print(type(sample_list))
print(sample_list)


<class 'list'>
[1, 'Yash', ['a', 'e']]


In [2]:
# importing "array" for array creations
import array as arr

# creating an array with integer type
a = arr.array('i', [1, 2, 3])
print(type(a))
for i in a:
	print(i, end=" ")


<class 'array.array'>
1 2 3 

# Q2. 
## Write a code to print the data type of each and every element of both the variables list_ and  arra_list.

In [5]:
lst = [22,'22','Ajay',(1,2,3)]
print("Given List : ", type(lst))
print("List:",lst )
j = 1
for i in lst:
    print(f'{j}th item type of the List : {type(i)}')
    j = j+1

Given List :  <class 'list'>
List: [22, '22', 'Ajay', (1, 2, 3)]
1th item type of the List : <class 'int'>
2th item type of the List : <class 'str'>
3th item type of the List : <class 'str'>
4th item type of the List : <class 'tuple'>


In [12]:
import array as arr
x  = arr.array('d',[1,2,3,4])
print("Given Array: ",x)
print("Type of Array: ",type(x))
j = 1
for i in x:
    print(f'{j}th item type  of the Array: {type(i)}')
    j+=1
    

Given Array:  array('d', [1.0, 2.0, 3.0, 4.0])
Type of Array:  <class 'array.array'>
1th item type  of the Array: <class 'float'>
2th item type  of the Array: <class 'float'>
3th item type  of the Array: <class 'float'>
4th item type  of the Array: <class 'float'>


# Q3. 
## Considering the following changes in the variable, array_list:
     array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list. 



### Consider the below code to answer further questions:
     import numpy as np
     num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
     num_array = np.array(object = num_list)
     
     
# Q4.
## Write a code to find the following characteristics of variable, num_array:
     (i) shape
    (ii) size     

In [24]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(type(num_array))
print(type(num_list))
print("Length of the List : ",len(num_list))
print("Size of the numpy Array : ",np.size(num_array))
print("Shape of the numpy Array : ",num_array.shape)


<class 'numpy.ndarray'>
<class 'list'>
Length of the List :  2
Size of the numpy Array :  6
Shape of the numpy Array :  (2, 3)


# Q5. 
## Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:

import numpy as np

a = np.zeros(3, dtype = int)
print("Matrix a : \n", a)

b = np.zeros([3, 3], dtype = int)
print("\nMatrix b : \n", b)


Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


# Q6. 
### Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [27]:
import numpy as np
x  = np.diag([1,1,1,1,1])
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


#### Completed 26Feb23_Assignment
# ___________________________________________________